export default {
    revenueChartCosmatics: {
        bgcolor: "#282A2E",
        canvasBgColor: "#282A2E",
        animation: "0",
        theme: "fusion",
        plotfillalpha: "15",
        plotFillAngle: "90",
        showCanvasBorder: "0",
        showLabels: "1",
        divLineAlpha: "50",
        divlineColor: "#434456",
        showYAxisValues: "1",
        showdivline: "1",
        yaxisminvalue: "1000000000",
        placeValuesInside: "0",
        showLegend: "0",
        showShadow: "0",
        paletteColors: "#62B58F",
        drawAnchors: "0",
        showAlternateHGridColor: "0",
        drawCrossLine: "0",
        plotColorinTooltip: "0",
        baseFontColor: "#ffffff",
        valueFontColor: "#b4b4b6",
        valueFontSize: "14",
        baseFontSize: "12",
        baseFont: "Roboto",
        toolTipBgColor: "#525357",
        toolTipColor: "#F8F8F8",
        toolTipBorderColor: "#525357",
        tooltipBorderAlpha: "20",
        showToolTipShadow: "1",
        toolTipPadding: "10",
        numberPrefix: "$",
        formatNumberScale: "1",
        numberScaleUnit: "B",
        numberScaleValue: "1000000000",
        plotToolText: "<b>Global Revenue</b></br><b>Year : </b>$label</br><b>Revenue :</b> $dataValue"

    },
    demographyChartCosmatics: {
        bgcolor: "#282A2E",
        pieRadius: "50",
        doughnutRadius: "40",
        paletteColors: "#D9D4F6,#8E81E3,#6957DA",
        canvasBgColor: "#282A2E",
        plotBorderalpha: "0",
        theme: "fusion",
        enableSlicing: "0",
        enableSmartLabels:"0",
        showHoverEffect:"0",
        plotHoverEffect:"0",
        enableRotation: "0",
        plotBorderHoverAlpha: "0",
        showlegend: "0",
        startingAngle: "90",
        valueFontColor: "#ffffff",
        labelFontColor: "#ffffff",
        smartLineColor: "#81809C",
        baseFontSize: "12",
        baseFontColor: "#61DAFB",
        toolTipBgColor: "#525357",
        toolTipColor: "#F8F8F8",
        toolTipBorderColor: "#525357",
        tooltipBorderAlpha: "20",
        showToolTipShadow: "1",
        toolTipPadding: "10",
        plotToolText: "<b>Age Group :</b> $label</br> <b>Subscribers :</b> $datavalue%"

    },
    subscriptionChartCosmatics: {
        theme: "fusion",
        bgcolor: "#282A2E",
        canvasBgColor: "#282A2E",
        paletteColors: "#6957DA",
        numbersuffix: "M",
        plotSpacePercent: "60",
        formatNumberScale: "1",
        showdivlineValues: "0",
        drawCrossLine: "1",
        crossLineColor: "#575961",
        crossLineAlpha: "15",
        showLimits: "0",
        showValues: "1",
        divlineAlpha: "0",
        baseFontSize: "12",
        baseFont: "Roboto",
        toolTipBgColor: "#525357",
        toolTipColor: "#F8F8F8",
        toolTipBorderColor: "#525357",
        tooltipBorderAlpha: "20",
        showToolTipShadow: "1",
        toolTipPadding: "10",
        plotToolText: "<b>Year :</b> $label </br><b>Subscribers :</b> $datavalue",
        labelFontColor: "#ffffff",
        valueFontColor: "#b4b4b6"

    },
    awardChartCosmatics: {
        bgcolor: "#282A2E",
        canvasBgColor: "#282A2E",
        showLabels: "1",
        drawCrossLine: "0",
        divLineAlpha: "0",
        showYAxisValues: "0",
        showValues: "1",
        placeValuesInside: "0",
        shadow: "0",
        legendPadding: "0",
        showShadow: "0",
        paletteColors: "#942F1C,#DD614A",
        drawAnchors: "0",
        showAlternateHGridColor: "0",
        legenditemfontcolor: "#ffffff",
        plotColorinTooltip: "0",
        valueFontColor: "#b4b4b6",
        labelFontColor: "#ffffff",
        baseFontSize: "12",
        baseFont: "Roboto",
        toolTipBgColor: "#525357",
        toolTipColor: "#F8F8F8",
        toolTipBorderColor: "#525357",
        tooltipBorderAlpha: "20",
        showToolTipShadow: "1",
        toolTipPadding: "10",
        plotToolText: "<b>Year :</b> $label</br><b>$seriesname :</b> $datavalue",
        theme: "fusion"

    },
    subregionChartCosmatics: {
        bgcolor: "#282A2E",
        canvasBgColor: "#282A2E",
        numbersuffix: "M",
        formatNumberScale: "0",
        baseFontSize: "12",
        baseFontColor:"#81809C",
        labelfontcolor:"#81809C",
        legendItemFontSize: "12",
        baseFont: "Roboto",
        showvalue: "0",
        showBorder: "1",
        borderAlpha: "80",
        fillAlpha: "100",
        borderColor: "#5F636E",
        borderThickness: "1",
        showHoverEffect: "1",
        showEntityHoverEffect: "1",
        labelFontcolor:"#81809C",
        legenditemfontcolor: "#ffffff",
        toolTipBgColor: "#525357",
        toolTipColor: "#F8F8F8",
        toolTipBorderColor: "#525357",
        tooltipBorderAlpha: "20",
        showToolTipShadow: "1",
        toolTipPadding: "10",
        legendBorderThickness: "5",
        entityToolText: "<b>Region : </b>$lname</br><b> Subscribers : </b>$dataValue",
        theme: "fusion"

    },
    imdbRatingChartCosmatics: {
        bgcolor: "#282A2E",
        paletteColors: "#C79E24",
        divlineAlpha: "0",
        canvasBgColor: "#282A2E",
        labelFontColor: "#ffffff",
        theme: "fusion",
        showDivLineValues: "0",
        showValues: "1",
        baseFont: "Roboto",
        valueFontColor: "#b4b4b6",
        plotSpacePercent: "60",
        axisLineAlpha: "80",
        showYAxisValues: "1",
        yaxislinecolor: "#434456",
        showYAxisLine: "1",
        showdivlineValues: "1",
        baseFontColor:"#ffffff",
        baseFontSize: "12",
        toolTipBgColor: "#525357",
        toolTipColor: "#F8F8F8",
        toolTipBorderColor: "#525357",
        tooltipBorderAlpha: "20",
        showToolTipShadow: "1",
        toolTipPadding: "10",
        anchorRadius: "60",
        plotToolText: "<b>$seriesName<b></br><b>Genre :</b> $label</br><b>Rating :</b> $Value"
    },
}